# Generated by Django 3.0.2 on 2020-07-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200709_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'searche'},
        ),
        migrations.AddField(
            model_name='search',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
